apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: dev
spec:
  ports:
  - nodePort: 32231
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: sample-app
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort
status:
  loadBalancer: {}
