apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "47"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"payplus-kafka-deployment"},"name":"payplus-kafka-deployment","namespace":"dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"payplus-kafka-deployment"}},"template":{"metadata":{"labels":{"app":"payplus-kafka-deployment"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"pub-sub","operator":"NotIn","values":["yes"]}]}]}}},"containers":[{"env":[{"name":"TOPIC","value":"all"},{"name":"MODE","value":"dev"}],"envFrom":[{"configMapRef":{"name":"kafka-cm"}}],"image":"713117837264.dkr.ecr.eu-west-2.amazonaws.com/paypluskafka:9aa7c0213d297783af64e51f60eb4dc712e33a48","name":"payplus-kafka-deployment"}]}}}}
    kubernetes.io/change-cause: kubectl set image deployment/payplus-kafka-deployment
      payplus-kafka-deployment=713117837264.dkr.ecr.eu-west-2.amazonaws.com/paypluskafka:090613416b77c160332774cdb00d4ecf84645c6a
      --namespace=dev --record=true
  creationTimestamp: "2023-10-26T10:04:44Z"
  generation: 47
  labels:
    app: payplus-kafka-deployment
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: kafka
    tags.datadoghq.com/version: "1"
  name: payplus-kafka-deployment
  namespace: dev
  resourceVersion: "131442807"
  uid: cd33bc26-80e5-4627-923b-f3a9eb6a26ad
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: payplus-kafka-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payplus-kafka-deployment
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: kafka
        tags.datadoghq.com/version: "1"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pub-sub
                operator: NotIn
                values:
                - "yes"
      containers:
      - env:
        - name: DD_ENV
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: env
          value: dev
        - name: TOPIC
          value: all
        - name: MODE
          value: dev
        envFrom:
        - configMapRef:
            name: kafka-cm
        image: 713117837264.dkr.ecr.eu-west-2.amazonaws.com/paypluskafka:090613416b77c160332774cdb00d4ecf84645c6a
        imagePullPolicy: IfNotPresent
        name: payplus-kafka-deployment
        resources:
          requests:
            cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-10T09:16:31Z"
    lastUpdateTime: "2024-01-10T09:16:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-26T10:04:44Z"
    lastUpdateTime: "2024-01-11T11:12:01Z"
    message: ReplicaSet "payplus-kafka-deployment-74976bf69" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 47
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
