apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: payplus-kafka-deployment
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: kafka
    tags.datadoghq.com/version: "1"
  name: payplus-kafka-deployment
  namespace: pp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payplus-kafka-deployment
  template:
    metadata:
      labels:
        app: payplus-kafka-deployment
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: kafka
        tags.datadoghq.com/version: "1"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pub-sub
                operator: NotIn
                values:
                - "yes"
      containers:
      - env:
        - name: TOPIC
          value: all
        - name: MODE
          value: production
        - name: DD_ENV
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: kafka-cm
        image: 713117837264.dkr.ecr.eu-west-2.amazonaws.com/paypluskafka:090613416b77c160332774cdb00d4ecf84645c6a
        imagePullPolicy: IfNotPresent
        name: payplus-kafka-deployment
        resources:
          requests:
            cpu: "2"
            memory: 8192M
